# Generated by Django 6.0.2 on 2026-03-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_author_post_user_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
    ]
