# Generated by Django 6.0.2 on 2026-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_comment_text_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
