# Generated by Django 6.0.2 on 2026-03-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
